version: "3"
services:
  mm-dashboard_phpfpm:
    build:
      context: .
      dockerfile: Dockerfile_phpfpm
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard}:${VERSION:-latest}
  mm-dashboard_nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: salmagundi_markten_mm-dashboard_nginx
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard-nginx}:${VERSION:-latest}
    command: >
      sh -c "sed -i /'fastcgi_param HTTPS on'/d /tmp/default.template;\
             envsubst '$$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf;\
             exec nginx -g 'daemon off;'"
    ports:
      - "127.0.0.1:8092:80"
