ARG NODE_VERSION=20.11.0

FROM node:$NODE_VERSION-alpine AS node
FROM nginx:1.25.4-alpine

RUN /sbin/apk update && /sbin/apk upgrade

RUN /sbin/apk add \
    nodejs \
    npm \
    yarn

COPY docker-nginx/default.template /tmp/default.template
COPY --chown=nginx ./public /var/www/public

COPY --chown=nginx ./assets /var/www/assets
COPY --chown=nginx ./package.json /var/www/package.json
COPY --chown=nginx ./yarn.lock /var/www/yarn.lock
COPY --chown=nginx ./webpack.config.js /var/www/webpack.config.js

WORKDIR /var/www

RUN yarn config set strict-ssl false
RUN yarn --ignore-scripts --ignore-platform && yarn encore prod

RUN chown -R nginx:nginx /etc/nginx

USER nginx

RUN envsubst '$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf

CMD exec nginx -g 'daemon off;'

EXPOSE 80
