version: "3.2"

services:
  web:
    build: .
    ports:
    - "8082:80"
    networks:
      - bridge
    volumes:
      - ./src:/app/src

networks:
  bridge:
    ipam:
      config:
        - subnet: 172.102.0.0/16
          gateway: 172.102.0.1
