version: "3"
services:
  mm-dashboard_phpfpm:
    build:
      dockerfile: Dockerfile_phpfpm
    container_name: salmagundi_markten_mm-dashboard_phpfpm
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard}:${VERSION:-latest}
    command: >
      sh -c "apk add --no-cache $$PHPIZE_DEPS ;\
             nslookup host.docker.internal || echo '172.172.0.1 host.docker.internal' >> /etc/hosts ;\
             pecl install xdebug-3.1.6 ;\
             docker-php-ext-enable xdebug ;\
             echo 'xdebug.mode=debug' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
             echo 'xdebug.client_host=host.docker.internal' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
             echo 'xdebug.client_port=9003' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
             echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
             echo 'xdebug.log=/var/www/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
             php-fpm -e"
    volumes:
      - /src:/var/www/src
      - /config:/var/www/config
      - /tests:/var/www/tests
      - /templates:/var/www/templates
      - /assets:/var/www/assets
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - MM_DASHBOARD__MAILER__TRANSPORT=smtp
      - MM_DASHBOARD__MAILER__HOST=mailhog
      - MM_DASHBOARD__MAILER__USER=salmagundi
      - MM_DASHBOARD__MAILER__PASSWORD=insecure
      - MM_DASHBOARD__MAILER__PORT=25
      - MM_DASHBOARD__MAILER__ENCRYPTION=none
      - APP_SECRET=insecure
      - MARKT_API=http://mm-api_nginx:80/api/1.1.0/
      - MM_APP_KEY=insecure
    networks:
      - salmagundi-dev-env

  mm-dashboard_nginx:
    build:
      dockerfile: Dockerfile_nginx
    container_name: salmagundi_markten_mm-dashboard_nginx
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard-nginx}:${VERSION:-latest}
    command: >
      sh -c "sed -i /'fastcgi_param HTTPS on'/d /tmp/default.template;\
             envsubst '$$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf;\
             exec nginx -g 'daemon off;'"
    depends_on:
      - mm-dashboard_phpfpm
    environment:
      - FASTCGI_PASS=mm-dashboard_phpfpm:9000
    networks:
      - salmagundi-dev-env
    ports:
      - "127.0.0.1:8092:80"


networks:
  salmagundi-dev-env:
    external:
      name: salmagundi-dev-env
