FROM nginx:stable-alpine

COPY certificates/adp_rootca.crt /usr/local/share/ca-certificates/adp_rootca.crt
RUN update-ca-certificates --fresh

RUN apk update && apk upgrade

RUN apk add \
    yarn

COPY docker-nginx/default.template /tmp/default.template
COPY --chown=nginx ./public /var/www/public

COPY --chown=nginx ./assets /var/www/assets
COPY --chown=nginx ./package.json /var/www/package.json
COPY --chown=nginx ./yarn.lock /var/www/yarn.lock
COPY --chown=nginx ./webpack.config.js /var/www/webpack.config.js

WORKDIR /var/www

RUN yarn && yarn encore prod

CMD envsubst '$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'

EXPOSE 80
