name: mm-dashboard
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: mm-dashboard

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'mm-dashboard'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app: {}

secrets:
  certificate:
    type: keyvault
    tls: markten
  php:
    type: keyvault
    secrets:
    # TODO rewrite to better env names?
      APP_KEY: api-key
      MARKT_API: api-url

deployments:
  mm-dashboard:
    image:
      repository: salmagundi/mm-dashboard
    securityContext:
      runAsUser: 82
    selectorLabels:
      component: phpfpm
    containers:
      - name: main
        ports:
          - port: 9000
            name: http
        volumes:
          - name: cache
            mountPath: /var/www/var/cache
          - name: logs
            mountPath: /var/www/var/log
          - name: tmp # sessions
            mountPath: /tmp
        secrets:
          - php
    volumes:
      - name: cache
        spec:
          emptyDir: {}
      - name: logs
        spec:
          emptyDir: {}
      - name: tmp
        spec:
          emptyDir: {}

  mm-dashboard-nginx:
    image:
      repository: salmagundi/mm-dashboard-nginx
    securityContext:
      runAsUser: 101
    selectorLabels:
      component: nginx
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        volumes:
          - name: logs
            mountPath: /var/log/nginx
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
    volumes:
      - name: logs
        spec:
          emptyDir: {}
      - name: run
        spec:
          emptyDir: {}
      - name: cache
        spec:
          emptyDir: {}

services:
  mm-dashboard-nginx:
    selector:
      component: nginx
    ports:
      - port: 8080
        targetPort: http
  mm-dashboard:
    selector:
      component: phpfpm
    ports:
      - port: 9000
        targetPort: http

ingress:
  mm-dashboard-nginx-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: mm-dashboard-nginx
        port: 8080
    tls: certificate

jobs:
  certificate-init:
    image:
      repository: salmagundi/mm-dashboard-nginx
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: certificate
    secrets:
      - certificate
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"
